# Generated by Django 5.1.13 on 2025-10-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('seed', models.CharField(blank=True, max_length=64)),
                ('guidance_scale', models.FloatField(blank=True, null=True)),
                ('grid_image', models.ImageField(blank=True, null=True, upload_to='cartoons/grids/')),
                ('fail_reason', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoons', to='diaries.diaryentry')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.JSONField(default=dict)),
                ('model', models.CharField(max_length=100)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='diaries.diaryentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CartoonPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cartoons/panels/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='generation.cartoon')),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('cartoon', 'index')},
            },
        ),
    ]
